### ISSUE TITLE
Can somebody explain how to use the session plzz 

### ISSUE THREAD

**Issue by mohsinxx365** [HendrixString/adobe-cep-react-create#20]

**Comment by HendrixString** [comment]
@mohsinxx365 
use session to speak with non front-end components such as backend logic,
desktop node modules etc..
session is bundled differently from client side.
all client side packages are in the root package.json, where
packages of session are in the session-src folder, they are bundled differently.

client side is packaged with each of it's dependency in a single file like classic web development,
where as session is not bundled with all it's dependencies into a single file because usually
for session-side there will be too many packages.

session is available everywhere through window.session property, but you can do what ever 
you want and even not use the session

**Comment by mohsinxx365** [comment]
Can u give me a code sample on how to use the session , It would be very helpful

**Comment by mohsinxx365** [comment]
And one more thing what is 'invoke document worker' and why is it in the evalscript function of the invokeplugin function

**Comment by HendrixString** [comment]
@mohsinxx365 
for session demo you can look in the code, there is a sample.
and 'invoke document worker' is just an old relic

**Comment by mohsinxx365** [comment]
Ok thanks !!
